name: buf actions

on:
  pull_request:
    branches:
      - main

jobs:

  lint-protos:
    name: Lint Proto
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with: 
          input: protobuf

  validate-protos:
    name: Validate Proto
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Run breaking change detection against the last commit
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: protobuf
          against: 'https://github.com/open-feature/open-feature-operator.git#branch=main,ref=HEAD~1,subdir=protobuf''
  
