name: "PR checks"

on:
  pull_request:

permissions:
  contents: read

env:
  GO_VERSION: 1.22

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
        with:
          version: '1.50.0'
          input: protobuf
          pr_comment: false

  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      
      # Use ajv to validate schema
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

      - name: Validate schema 
        run: make ajv-validate-flagd-schema

      # Run go test suite to validate the json schema against positive and/or negative validations in /json/test
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Validate Schema
        run: make test

      # Ensure there is no diff when make gen-schema-json is run 
      - run: make gen-schema-json
      - name: Check no diff 
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then echo "JSON schema generation produced diff. Run 'make gen-schema-json' and commit results."; exit 1; fi
